### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by porChe1223** [porChe1223/Tonkatsu___Ito_2#4]

**Comment by KOU050223** [comment]
2人用まで実装
2人集まったら部屋の状態が変更される
ユーザーはplayroomにリダイレクトする

## 今後

- [ ] 最大数を弄れる
- [ ] ユーザーがroomの状態を変更できるようにする（最大数集まらなくても開始できる）
- [ ] room作成機能
- [ ] room番号（room_id）を選択して入室する機能

**Comment by KOU050223** [comment]
gameroomとの繋げるところ要修正
ゲームのお題とカード番号を振り分けるところを考える
